### ISSUE TITLE
Stylelint Formatting is not working

### ISSUE THREAD

**Issue by monsonjeremy** [jose-elias-alvarez/null-ls.nvim#239]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev+nightly-713-gdd7812ec6

### Steps to reproduce

- Use the `null-ls` formatting builtin for `stylelint`
- Attempt to format a `.scss` file

### Expected behavior

Formatting should apply changes to the file

### Actual behavior

No changes are made to the file

### Debug log

```
null-ls log: /Users/redacted/.cache/nvim/null-ls.log
Detected filetype: scss

1 source(s) active for this buffer:

Formatting: stylelint
```

```
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP request for method initialize
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method initialized
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP notification for method textDocument/didOpen
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: no generators available
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received diagnostics from generators
[DEBUG Tue Oct  5 11:14:09 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: {}
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received LSP request for method textDocument/formatting
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: running generators for method NULL_LS_FORMATTING
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: spawning command stylelint with args:
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: { "--fix", "--stdin", "--config", "/Users/redacted/dotfiles/.stylelintrc.json", "-" }
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: error output: Error: No files matching the pattern "-" were found.
    at /Users/redacted/.fnm/node-versions/v12.21.0/installation/lib/node_modules/stylelint/lib/standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: output: nil
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: received edits from generators:
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: {}
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: successfully applied edits:
[DEBUG Tue Oct  5 11:14:25 2021] .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/utils.lua:51: {}
```

### Help

Yes

**Comment by olejech** [comment]
> @chuckmasucciМожете ли вы открыть отдельную проблему и следовать инструкциям, чтобы включить ведение журнала отладки и опубликовать свой журнал отладки? Можете ли вы также проверить, работает ли запуск `stylelint --fix`файла из командной строки?

It's not working only capitalized file names, example — **Users.module.scss**
